### ISSUE TITLE
Valid js, invalid module

### ISSUE THREAD

**Issue by qfox** [node-eval/node-eval#4]
Should we consider invalid exports as an error?

I've got an error for this:

``` js
module.export = {}; // instead of .exports
```

`Error at evaluating bemjson: ReferenceError: module is not defined`

But I guess it should result in `undefined` because exports is empty.

What you think?

**Comment by Yeti-or** [comment]
so you suggest to put tryCatch over evaluating `({})` expression statements?

**Comment by qfox** [comment]
No, I'm about the first run: https://github.com/gulp-bem/node-eval/blob/master/index.js#L42-L44

Here we should return undefined, right?

**Comment by Yeti-or** [comment]
actually problem is in another place.
you write to `module.somProp` so in https://github.com/gulp-bem/node-eval/blob/master/index.js#L47
we check only for changes in exports and eval code again so in the second run you have a problem:
`module is undefined` yes it is

**Comment by Yeti-or** [comment]
fix in #11 && #5
