### ISSUE TITLE
Can't parse this while this can be executed in browser console.

### ISSUE THREAD

**Issue by tpikachu** [node-eval/node-eval#44]
[]+[][(![]+[])[((!+[]+(!!!![])+!(!!![]))+[])]+(+{}+[]+[]+{})[((((!+([])+(!+[])+!(!!![])+!!!![])))+[])]+(!![]+[])[((((((((+(!!!![]))))))))+[])]+(!![]+[])[(((((((+!!!([])))))))+[])]][([]+{})[(!+([])+(!!!![])+!!!!([])+!!(!![])+!!!(![])+[])]+([]+{})[(((((+!!!(![])))))+[])]+([][[]]+[])[((((!+[])+!!!(![])+!!!!([])+!!!![]+!(![])+!(+[])))+[])]+(![]+[])[((!+[]+(!!!![])+!(!!![]))+[])]+(+((((((((+!!([])))))))+[])+(![]+[])[((((((((!+[])+(!!!![])+(!+[])+!(+[])))))))+[])]+(((+(!![])))+[])+((((((((+!(!![]))))))))+[])+(((((((+!!(![])))))))+[])+((((((+!!![])+(+!!![])))))+[]))+[])[(((((((!(+[])+!(!!![])+(!+[])+!(!!![])+!(+[])+(!+[])))))))+[])]+(!![]+[])[((((((((+(!!!![]))))))))+[])]+(!![]+[])[((((((!+[]+!!(!![]))))))+[])]+([]+{})[(!+([])+(!!!![])+!!!!([])+!!(!![])+!!!(![])+[])]+([]+{})[((((+!!(!![]))))+[])+((((((((!+[])+(!+[])+!+([])))))))+[])]+([]+{})[(((((+!!!(![])))))+[])]+(!![]+[])[((((((((+(!!!![]))))))))+[])]]((!![]+[])[((((((((+(!!!![]))))))))+[])]+([]+{})[((((((+!!!(![]))))))+[])+(+(!+[])+[])]+(+{}+[]+!![]+[])[(((((!+([])+!!(!![])+!(![])))))+[])]+(!![]+[])[((((((!+[]+!!(!![]))))))+[])]+(!![]+[])[((((((((+(!!!![]))))))))+[])]+([][[]]+[])[((((!+[])+!!!(![])+!!!!([])+!!!![]+!(![])+!(+[])))+[])]+([]+{})[((!+[]+!!(!![])+(!![])+(!+[])+!!!(![])+!(![])+!+[])+[])]+(![]+[])[((!(+[])+!(!!![]))+[])]+([]+{})[(((((+!!!(![])))))+[])]+([]+{})[(((((+!!(!![])))))+[])+(((((((!+([])+!(!!![])))))))+[])]+(![]+[])[(+!+[]+[])]+(+((((((((+!!([])))))))+[])+(![]+[])[((((((((!+[])+(!!!![])+(!+[])+!(+[])))))))+[])]+(((+(!![])))+[])+((((((((+!(!![]))))))))+[])+(((((((+!!(![])))))))+[])+((((((+!!![])+(+!!![])))))+[]))+[])[(((((((!(+[])+!(!!![])+(!+[])+!(!!![])+!(+[])+(!+[])))))))+[])]+(+((((((((+!!([])))))))+[])+(![]+[])[((((((((!+[])+(!!!![])+(!+[])+!(+[])))))))+[])]+(((+(!![])))+[])+((((((((+!(!![]))))))))+[])+(((((((+!!(![])))))))+[])+((((((+!!![])+(+!!![])))))+[]))+[])[(((((!+([])+!!!![]+!!!(![])))))+[])]+([]+{})[(((((+!!!(![])))))+[])]+([][[]]+[])[((((+(!+[]))))+[])])())[(((((((!+([])+!(!!![])+!(!!![])+!+([])+!!!(![])+!(!!![])))))))+[])]+(![]+[])[((((((((+![])+(+![])))))))+[])]

**Comment by Yeti-or** [comment]
<img width="471" alt="Sceenshot" src="https://user-images.githubusercontent.com/1813468/100407074-80cc1800-3078-11eb-84bb-7a8f48274a8a.png">
@tpikachu are u sure it's a valid syntax ?

**Comment by Yeti-or** [comment]
actually it works with code created through http://www.jsfuck.com/

https://runkit.com/embed/si0xsk6a6sbj
